"""Technical Agent — Indicators, patterns, entry/exit signals.

Responsibilities:
    1. Compute indicators (RSI, MACD, EMA, ATR, Bollinger Bands).
    2. Detect chart patterns (breakouts, reversals).
    3. Generate BUY / SELL / HOLD signals per strategy.
    4. Calculate dynamic stop-loss and target prices.

This is the heart of Phase 1. Strategies plug in here.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional

import pandas as pd


class SignalType(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    EXIT = "EXIT"


@dataclass
class Signal:
    """A trade signal generated by a strategy."""
    symbol: str
    signal_type: SignalType
    entry_price: float
    stop_loss: float
    target: float
    timestamp: datetime
    strategy_name: str
    confidence: float = 0.5             # 0.0 – 1.0
    reasoning: str = ""                 # Human-readable explanation


class TechnicalAgent:
    """Computes indicators and generates trade signals."""

    def __init__(self, config: dict):
        self.config = config
        self.ind_cfg = config.get("indicators", {})

    # ------------------------------------------------------------------
    # Indicator computation
    # ------------------------------------------------------------------
    def add_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """Add all standard indicators to OHLCV dataframe.

        Expects df with columns: open, high, low, close, volume.
        """
        try:
            import pandas_ta as ta
        except ImportError:
            raise ImportError("pandas-ta not installed — pip install pandas-ta")

        df = df.copy()
        df["rsi"] = ta.rsi(df["close"], length=self.ind_cfg.get("rsi_period", 14))
        df["ema_fast"] = ta.ema(df["close"], length=self.ind_cfg.get("ema_fast", 9))
        df["ema_slow"] = ta.ema(df["close"], length=self.ind_cfg.get("ema_slow", 21))
        df["ema_trend"] = ta.ema(df["close"], length=self.ind_cfg.get("ema_trend", 50))

        macd = ta.macd(
            df["close"],
            fast=self.ind_cfg.get("macd_fast", 12),
            slow=self.ind_cfg.get("macd_slow", 26),
            signal=self.ind_cfg.get("macd_signal", 9),
        )
        if macd is not None:
            df = pd.concat([df, macd], axis=1)

        df["atr"] = ta.atr(
            df["high"], df["low"], df["close"],
            length=self.ind_cfg.get("atr_period", 14),
        )
        return df

    # ------------------------------------------------------------------
    # Signal generation
    # ------------------------------------------------------------------
    def generate_signal(
        self,
        symbol: str,
        df: pd.DataFrame,
        strategy_name: str,
    ) -> Optional[Signal]:
        """Generate a signal by delegating to a strategy module.

        Strategies live under strategies/<name>.py and expose a
        `generate_signal(df, config) -> Signal | None` function.
        """
        # TODO: dynamic import from strategies/<strategy_name>.py
        return None

    # ------------------------------------------------------------------
    # Stop-loss / Target calculation
    # ------------------------------------------------------------------
    def calc_stoploss(self, entry_price: float, atr: float, mode: str = "atr") -> float:
        """Compute stop-loss price.

        Modes:
            "atr"     → entry - 2*ATR (volatility-adjusted)
            "percent" → entry * (1 - default_stoploss_pct/100)
        """
        if mode == "atr" and atr > 0:
            return entry_price - 2 * atr
        sl_pct = self.config["risk"]["default_stoploss_pct"]
        return entry_price * (1 - sl_pct / 100)

    def calc_target(self, entry_price: float, stoploss: float, rr: float = 2.0) -> float:
        """Compute target price using risk-reward ratio (default 1:2)."""
        risk = entry_price - stoploss
        return entry_price + rr * risk
